springdoc:
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    #    org.springdoc: DEBUG
    #    org.springdoc.core: DEBUG
    root: DEBUG
    org: INFO
    org.springframework: INFO
    org.apache: INFO
    sun: INFO
    javax: INFO
    io: INFO
    jdk: INFO
    jakarta: INFO
    org.springdoc: DEBUG
#    org.springdoc.core: DEBUG
#    org.springdoc.api: DEBUG
#    org.springdoc.webmvc: DEBUG
#    org.springdoc.ui: DEBUG
